framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                default_middleware: true

            query.bus:
                default_middleware: true

            event.bus:
                default_middleware: true

        transports:
            command_async:
                dsn: '%env(MESSENGER_COMMAND_TRANSPORT_DSN)%'
                options:
                    queues:
                        command_async: ~

            event_async:
                dsn: '%env(MESSENGER_EVENT_TRANSPORT_DSN)%'
                options:
                    queues:
                        event_async: ~

            query_sync:
                dsn: '%env(MESSENGER_QUERY_TRANSPORT_DSN)%'

        routing:
            App\Shared\Domain\Bus\CommandMessageInterface: command_async
            App\Shared\Domain\Bus\QueryMessageInterface: query_sync
            App\Shared\Domain\Bus\EventMessageInterface: event_async
